load("//build_defs:cpp_opts.bzl", "COPTS")
load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "network_all_test",
    srcs = glob(
        [
            "*_test.cpp",
            "*.h",
        ],
        allow_empty = True,
    ),
    copts = COPTS,
    deps = [
        "//network",
        "//network/test/proto:book_cc_proto",
        "@fmt",
        "@googletest//:gtest",
        "@nlohmann_json//:json",
        "@googletest//:gtest_main",
    ],
)
