load("@pycstl_deps//:requirements.bzl", "requirement")
load("@rules_python//python:py_library.bzl", "py_library")
load("@rules_python//python:py_test.bzl", "py_test")

py_library(
    name = "micrograd",
    srcs = glob(["micrograd/*.py"]),
    imports = [""],
)

py_test(
    name = "micrograd_test",
    srcs = ["test/engine_test.py"],
    main = "test/engine_test.py",
    deps = [
        requirement("numpy"),
        requirement("torch"),
        ":micrograd",
    ],
)
