load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")

cc_library(
    name = "status_server_lib",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    copts = COPTS,
    strip_include_prefix = "include",
    deps = [
        "//chat/common",
        "//chat/server/common:config_mgr",
        "//chat/server/common:redis_mgr",
        "//chat/server/common:utils",
        "//chat/server/proto:status_cc_grpc_proto",
        "//logger",
        "@fmt",
        "@grpc//:grpc++",
    ],
)

cc_binary(
    name = "status_server",
    srcs = ["status_server.cpp"],
    copts = COPTS,
    visibility = ["//chat/server:__subpackages__"],
    deps = [
        ":status_server_lib",
        "//chat/server/common:config_mgr",
        "@boost.asio",
    ],
)
