"""c++ project build by bazel"""

module(
    name = "pycstl",
    version = "0.0.1",
)

_ALL_CONTENT = """\
filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
"""

git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

#-------------------------------------------------------------------------------------
# C++
#-------------------------------------------------------------------------------------

# 1. The metadata of glog is fetched from the BCR, including its dependencies (gflags).
# 2. The `repo_name` attribute allows users to reference this dependency via the `gtest` repo name.
BOOST_VERSION = "1.90.0"

bazel_dep(name = "boost.asio", version = BOOST_VERSION + ".bcr.1")
bazel_dep(name = "boost.beast", version = BOOST_VERSION + ".bcr.1")
bazel_dep(name = "boost.property_tree", version = BOOST_VERSION + ".bcr.1")
bazel_dep(name = "boost.uuid", version = BOOST_VERSION + ".bcr.1")
bazel_dep(name = "eigen", version = "5.0.1.bcr.2")
bazel_dep(name = "fmt", version = "12.2.0")
bazel_dep(name = "gflags", version = "2.3.1")
bazel_dep(name = "glm", version = "1.0.3")
bazel_dep(name = "grpc", version = "1.83.0")
bazel_dep(name = "hiredis", version = "1.3.0")
bazel_dep(name = "imgui", version = "1.92.2")
bazel_dep(name = "nlohmann_json", version = "3.12.0.bcr.1")
bazel_dep(name = "platforms", version = "1.1.0")  # rules_qt need it
bazel_dep(name = "protobuf", version = "35.1")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")
bazel_dep(name = "spdlog", version = "1.17.0")

# mysql-connector-cpp
bazel_dep(name = "mysql-connector-cpp")
local_path_override(
    module_name = "mysql-connector-cpp",
    path = "third_party/mysql-connector-cpp",
)

# imgui_backends
bazel_dep(name = "imgui_backends")
local_path_override(
    module_name = "imgui_backends",
    path = "third_party/imgui/backends",
)

bazel_dep(name = "toolchains_llvm", version = "1.8.0")

# Configure and register the toolchain.
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    llvm_version = "21.1.8",
    stdlib = {"linux-x86_64": "stdc++"},
)
use_repo(llvm, "llvm_toolchain")
# use_repo(llvm, "llvm_toolchain_llvm") # if you depend on specific tools in scripts

register_toolchains("@llvm_toolchain//:all")

#-------------------------------------------------------------------------------------
# SDL2/SDL3
#-------------------------------------------------------------------------------------

git_repository(
    name = "sdl2",
    build_file_content = _ALL_CONTENT,
    remote = "https://github.com/libsdl-org/SDL.git",
    tag = "release-2.32.10",
)

git_repository(
    name = "sdl2_image",
    build_file_content = _ALL_CONTENT,
    init_submodules = True,
    remote = "https://github.com/libsdl-org/SDL_image.git",
    tag = "release-2.8.8",
)

git_repository(
    name = "sdl2_mixer",
    build_file_content = _ALL_CONTENT,
    init_submodules = True,
    remote = "https://github.com/libsdl-org/SDL_mixer.git",
    tag = "release-2.8.1",
)

git_repository(
    name = "sdl2_ttf",
    build_file_content = _ALL_CONTENT,
    init_submodules = True,
    remote = "https://github.com/libsdl-org/SDL_ttf.git",
    tag = "release-2.24.0",
)

git_repository(
    name = "sdl3",
    build_file_content = _ALL_CONTENT,
    remote = "https://github.com/libsdl-org/SDL.git",
    tag = "release-3.2.28",
)

git_repository(
    name = "sdl3_image",
    build_file_content = _ALL_CONTENT,
    init_submodules = True,
    remote = "https://github.com/libsdl-org/SDL_image.git",
    tag = "release-3.2.4",
)

git_repository(
    name = "sdl3_mixer",
    build_file_content = _ALL_CONTENT,
    commit = "e777b524e8f854c6c6590e2b5766bb1cee52e016",
    init_submodules = True,
    remote = "https://github.com/libsdl-org/SDL_mixer.git",
)

git_repository(
    name = "sdl3_ttf",
    build_file_content = _ALL_CONTENT,
    init_submodules = True,
    remote = "https://github.com/libsdl-org/SDL_ttf.git",
    tag = "release-3.2.2",
)

# SDL2
bazel_dep(name = "sdl2_gfx")
local_path_override(
    module_name = "sdl2_gfx",
    path = "third_party/sdl2_gfx",
)

bazel_dep(name = "entt")
git_override(
    module_name = "entt",
    commit = "85c6bba014049b5de8fad49d25424df2f1f6a8c1",  # v4.0.0
    remote = "https://github.com/skypjack/entt",
)

#-------------------------------------------------------------------------------------
# Qt6
#-------------------------------------------------------------------------------------

bazel_dep(name = "rules_qt", version = "0.0.7")

qt = use_extension("@rules_qt//extension:qt.bzl", "fetch")
qt.install(
    name = "qt_linux_x86_64",
    build_file = "@rules_qt//extension:qt/6.8.3/linux_x86_64.BUILD",
    os = "linux_x86_64",
    version = "6.8.3",
)
use_repo(qt, "qt_linux_x86_64")

register_toolchains(
    "@rules_qt//tools:all",
)

#-------------------------------------------------------------------------------------
# Node.js
#-------------------------------------------------------------------------------------

bazel_dep(name = "aspect_rules_js", version = "3.4.0")

####### Node.js version #########
# By default you get the node version from DEFAULT_NODE_VERSION in @rules_nodejs//nodejs:repositories.bzl
# Optionally you can pin a different node version:
# bazel_dep(name = "rules_nodejs", version = "6.2.0")
# node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node", dev_dependency = True)
# node.toolchain(node_version = "16.14.2")
#################################

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm", dev_dependency = True)
npm.npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)
use_repo(npm, "npm")

pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm")

# Allows developers to use the matching pnpm version, for example:
# bazel run -- @pnpm --dir $PWD install --lockfile-only
use_repo(pnpm, "pnpm")

#-------------------------------------------------------------------------------------
# Python
#-------------------------------------------------------------------------------------

bazel_dep(name = "rules_python", version = "2.3.1")

PYTHON_VERSION = "3.12"

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    configure_coverage_tool = False,
    ignore_root_user_error = True,
    python_version = PYTHON_VERSION,
)

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pycstl_deps",
    python_version = PYTHON_VERSION,
    requirements_lock = "//:requirements_lock.txt",
)
use_repo(pip, "pycstl_deps")

#-------------------------------------------------------------------------------------
# Test only
#-------------------------------------------------------------------------------------

bazel_dep(name = "googletest", version = "1.18.0", dev_dependency = True)
bazel_dep(name = "google_benchmark", version = "1.9.5", dev_dependency = True)

# 导出 compile_commands.json
# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    commit = "f5fbd4cee671d8d908f37c83abaf70fba5928fc7",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    # Replace the commit hash (above) with the latest (https://github.com/hedronvision/bazel-compile-commands-extractor/commits/main).
    # Even better, set up Renovate and let it do the work for you (see "Suggestion: Updates" in the README).
)
