load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//build_defs:cpp_opts.bzl", "COPTS")

package(features = ["-layering_check"])

cc_binary(
    name = "shooter",
    srcs = glob([
        "src/**/*.cpp",
        "include/**/*.h",
    ]),
    copts = COPTS,
    data = glob(["assets/**"]),
    includes = ["include"],
    deps = [
        "//common",
        "//sdl2",
        "//sdl2:sdl2_image",
        "//sdl2:sdl2_mixer",
        "//sdl2:sdl2_ttf",
    ],
)
