load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//build_defs:cpp_opts.bzl", "COPTS")

cc_binary(
    name = "shooter",
    srcs = glob([
        "src/**/*.cpp",
        "include/**/*.h",
    ]),
    copts = COPTS,
    data = glob(["assets/**"]),
    features = ["-layering_check"],
    includes = ["include"],
    deps = [
        "//common:singleton",
        "//sdl2",
        "//sdl2:sdl2_image",
        "//sdl2:sdl2_mixer",
        "//sdl2:sdl2_ttf",
        "@fmt",
    ],
)
