load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")

cc_library(
    name = "shooter_lib",
    srcs = glob(["shooter/*.cpp"]),
    hdrs = glob(["shooter/*.h"]),
    copts = COPTS,
    features = ["-layering_check"],
    strip_include_prefix = "/sdl2/shooter",
    deps = [
        "//common:singleton",
        "//sdl2",
        "//sdl2:sdl2_image",
        "//sdl2:sdl2_mixer",
        "//sdl2:sdl2_ttf",
        "@fmt",
    ],
)

cc_binary(
    name = "shooter",
    srcs = ["main.cpp"],
    copts = COPTS,
    data = glob(["assets/**"]),
    deps = [":shooter_lib"],
)
