load("//build_defs:cpp_opts.bzl", "COPTS")
load("@rules_cc//cc:defs.bzl", "cc_binary")

BINARIES = [
    "exception_handle",
    "variant_result",
    "template_task",
    "sleep_for",
    "simple_when_all",
    "when_all",
    "when_any",
]

[cc_binary(
    name = binary,
    srcs = ["%s.cpp" % binary],
    copts = COPTS,
    deps = [
        "//logger",
        "@fmt",
    ],
) for binary in BINARIES]
