load("@rules_qt//:qt.bzl", "qt_cc_binary", "qt_cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")
load("//chat/client/widget:widgets.bzl", "WIDGETS")

qt_cc_library(
    name = "client_lib",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    copts = COPTS,
    features = ["-layering_check"],
    strip_include_prefix = "include",
    deps = [
        "//chat/client/widget:%s_ui" % widget
        for widget in WIDGETS
    ] + [
        "//chat/common",
        "//common:singleton",
        "@rules_qt//:qt_network",
        "@rules_qt//:qt_widgets",
    ],
)

qt_cc_binary(
    name = "client",
    srcs = ["main.cpp"],
    copts = COPTS,
    data = glob([
        "config/*",
        "res/*",
        "style/*",
    ]),
    features = ["-layering_check"],
    deps = [
        ":client_lib",
    ],
)
