load("//build_defs:cpp_opts.bzl", "COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pycstl",
    hdrs = glob(["include/pycstl/**/*.h"]),
    copts = COPTS,
    includes = ["include"],
    deps = [
        "//common",
        "@fmt",
    ],
)
