load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")

cc_library(
    name = "tetris_lib",
    srcs = glob(["tetris/*.cpp"]),
    hdrs = glob(["tetris/*.h"]),
    copts = COPTS,
    strip_include_prefix = "/tetris",
    deps = [
        "//common:singleton",
        "@fmt",
    ],
)

cc_binary(
    name = "tetris",
    srcs = ["tetris.cpp"],
    copts = COPTS,
    data = glob(["resource/**"]),
    deps = [":tetris_lib"],
)
