load("//build_defs:cpp_opts.bzl", "COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    copts = COPTS,
    includes = ["include"],
    deps = [
        "//sdl2",
        "//sdl2:sdl2_image",
        "//sdl2:sdl2_mixer",
        "//sdl2:sdl2_ttf",
        "@eigen",
        "@fmt",
    ],
)
