load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")

cc_library(
    name = "chicken_evil_lib",
    srcs = glob(["chicken_evil/*.cpp"]),
    hdrs = glob(["chicken_evil/*.h"]),
    copts = COPTS,
    features = ["-layering_check"],
    strip_include_prefix = "/sdl2/chicken_evil",
    deps = [
        "//common:singleton",
        "//sdl2/common",
        "@eigen",
        "@fmt",
    ],
)

cc_binary(
    name = "chicken_evil",
    srcs = ["main.cpp"],
    copts = COPTS,
    data = glob(["assets/**"]),
    deps = [":chicken_evil_lib"],
)
