load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")

cc_library(
    name = "chicken_evil_lib",
    srcs = glob(["chicken_evil/*.cpp"]),
    copts = COPTS,
    features = [
        "cpp_modules",
        "-layering_check",
    ],
    module_interfaces = glob(["chicken_evil/*.cppm"]),
    deps = [
        "//common:singleton",
        "//sdl2/common",
        "@eigen",
        "@fmt",
    ],
)

cc_binary(
    name = "chicken_evil",
    srcs = ["main.cpp"],
    copts = COPTS,
    data = glob(["assets/**"]),
    features = ["cpp_modules"],
    deps = [":chicken_evil_lib"],
)
