load("//build_defs:cpp_opts.bzl", "COPTS")
load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "chicken_evil",
    srcs = glob([
        "src/**/*.cpp",
        "include/**/*.h",
    ]),
    copts = COPTS,
    data = glob(["assets/**"]),
    includes = ["include"],
    deps = [
        "//common",
        "//sdl2/common",
    ],
)
