load("//build_defs:cpp_opts.bzl", "COPTS")
load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "tiny_db",
    srcs = glob([
        "src/*.cpp",
        "include/tiny_db/*.h",
    ]),
    copts = COPTS,
    includes = ["include"],
    deps = ["@fmt"],
)
