load("@rules_cc//cc:defs.bzl", "cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")

cc_library(
    name = "network",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/network/**/*.h"]),
    copts = COPTS,
    strip_include_prefix = "include",
    visibility = ["//network:__subpackages__"],
    deps = [
        "//common:noncopyable",
        "//common:singleton",
        "//network/proto:msg_cc_proto",
        "@boost.asio",
        "@boost.beast",
        "@boost.uuid",
        "@fmt",
        "@nlohmann_json//:json",
    ],
)
