load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

cmake(
    name = "sdl2",
    build_args = ["-j8"],
    cache_entries = {"SDL_STATIC_ENABLED_BY_DEFAULT": "OFF"},
    generate_args = ["-GNinja"],
    includes = ["SDL2"],
    lib_source = "@sdl2//:all_srcs",
    out_shared_libs = select({
        "//conditions:default": [
            "libSDL2-2.0.so",
            "libSDL2-2.0.so.0",
        ],
        "//:debug": [
            "libSDL2-2.0d.so",
            "libSDL2-2.0d.so.0",
        ],
    }),
    visibility = ["//visibility:public"],
)

cmake(
    name = "sdl2_image",
    build_args = ["-j8"],
    build_data = ["@nasm"],
    cache_entries = {"SDL2IMAGE_VENDORED": "ON"},
    env = {"ASM_NASM": "$(execpath @nasm)"},
    generate_args = ["-GNinja"],
    lib_source = "@sdl2_image//:all_srcs",
    out_shared_libs = select({
        "//conditions:default": [
            "libSDL2_image-2.0.so",
            "libSDL2_image-2.0.so.0",
        ],
        "//:debug": [
            "libSDL2_image-2.0d.so",
            "libSDL2_image-2.0d.so.0",
        ],
    }),
    visibility = ["//visibility:public"],
    deps = ["sdl2"],
)

cmake(
    name = "sdl2_mixer",
    build_args = ["-j8"],
    cache_entries = {"SDL2MIXER_VENDORED": "ON"},
    generate_args = ["-GNinja"],
    lib_source = "@sdl2_mixer//:all_srcs",
    out_shared_libs = select({
        "//conditions:default": [
            "libSDL2_mixer-2.0.so",
            "libSDL2_mixer-2.0.so.0",
        ],
        "//:debug": [
            "libSDL2_mixer-2.0d.so",
            "libSDL2_mixer-2.0d.so.0",
        ],
    }),
    visibility = ["//visibility:public"],
    deps = ["sdl2"],
)

cmake(
    name = "sdl2_ttf",
    build_args = ["-j8"],
    cache_entries = {"SDL2TTF_VENDORED": "ON"},
    generate_args = ["-GNinja"],
    lib_source = "@sdl2_ttf//:all_srcs",
    out_shared_libs = select({
        "//conditions:default": [
            "libSDL2_ttf-2.0.so",
            "libSDL2_ttf-2.0.so.0",
        ],
        "//:debug": [
            "libSDL2_ttf-2.0d.so",
            "libSDL2_ttf-2.0d.so.0",
        ],
    }),
    visibility = ["//visibility:public"],
    deps = ["sdl2"],
)
