load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "gate_server_lib",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    copts = COPTS,
    includes = ["include"],
    deps = [
        "//chat/common",
        "//chat/server/common",
        "//chat/server/proto:verify_cc_grpc_proto",
        "//chat/server/proto:verify_cc_proto",
        "//common",
        "//logger",
        "@boost.asio",
        "@boost.beast",
        "@grpc//:grpc++",
        "@nlohmann_json//:json",
    ],
)

cc_binary(
    name = "gate_server",
    srcs = ["gate_server.cpp"],
    copts = COPTS,
    deps = [
        ":gate_server_lib",
        "//chat/server/common",
    ],
)
