load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")

cc_library(
    name = "gate_server_lib",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    copts = COPTS,
    strip_include_prefix = "include",
    deps = [
        "//chat/common",
        "//chat/server/common:config_mgr",
        "//chat/server/common:defer",
        "//chat/server/common:io_service_pool",
        "//chat/server/common:mysql_mgr",
        "//chat/server/common:redis_mgr",
        "//chat/server/common:status_grpc_client",
        "//chat/server/proto:verify_cc_grpc_proto",
        "//chat/server/proto:verify_cc_proto",
        "//common:connection_pool",
        "//common:singleton",
        "//common:utils",
        "//logger",
        "@boost.asio",
        "@boost.beast",
        "@grpc//:grpc++",
        "@nlohmann_json//:json",
    ],
)

cc_binary(
    name = "gate_server",
    srcs = ["gate_server.cpp"],
    copts = COPTS,
    visibility = ["//chat/server:__subpackages__"],
    deps = [
        ":gate_server_lib",
        "//chat/server/common:config_mgr",
    ],
)
