load("@rules_qt//:qt.bzl", "qt_cc_binary", "qt_cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")

package(
    default_visibility = ["//visibility:public"],
    features = ["-layering_check"],
)

qt_cc_library(
    name = "notepad_lib",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    copts = COPTS,
    includes = ["include"],
    deps = [
        "@rules_qt//:qt_widgets",
    ],
)

qt_cc_binary(
    name = "notepad",
    srcs = ["main.cpp"],
    copts = COPTS,
    data = glob([
        "res/*",
    ]),
    deps = [
        ":notepad_lib",
    ],
)
