load("//build_defs:cpp_opts.bzl", "STRICT_COPTS")
load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "common_test",
    srcs = glob([
        "*.cpp",
        "*.h",
    ]),
    copts = STRICT_COPTS,
    deps = [
        "//chat/server/common",
        "@googletest//:gtest_main",
    ],
)
