load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//build_defs:cpp_opts.bzl", "COPTS")

cc_binary(
    name = "entt_example",
    srcs = [
        "entt_base.cpp",
        "entt_example.cpp",
        "entt_signal.cpp",
        "entt_struct.h",
    ],
    copts = COPTS,
    deps = [
        "@entt",
        "@fmt",
        "@glm",
    ],
)

cc_binary(
    name = "imgui_example",
    srcs = [
        "imgui_example.cpp",
    ],
    copts = COPTS,
    data = glob(["assets/**"]),
    features = ["-layering_check"],
    deps = [
        "//sdl3:sdl3_image",
        "@bazel_tools//tools/cpp/runfiles",
        "@glm",
        "@imgui",
        "@imgui_backends//:platform-sdl3",
        "@imgui_backends//:renderer-sdlrenderer3",
        "@spdlog",
    ],
)
