load("//build_defs:cpp_opts.bzl", "STRICT_COPTS")

cc_binary(
    name = "entt_example",
    srcs = [
        "entt_base.cpp",
        "entt_example.cpp",
        "entt_signal.cpp",
        "entt_struct.h",
    ],
    copts = STRICT_COPTS,
    deps = [
        "@entt",
        "@fmt",
        "@glm",
    ],
)
