load("//build_defs:cpp_opts.bzl", "COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files(["LICENSE"])

cc_library(
    name = "common",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    copts = COPTS,
    data = glob(["config/*"]),
    includes = ["include"],
    deps = [
        "//chat/common",
        "//chat/server/proto:status_cc_grpc_proto",
        "//common",
        "//logger",
        "@boost.asio",
        "@boost.property_tree",
        "@boost.uuid",
        "@fmt",
        "@grpc//:grpc++",
        "@hiredis",
        "@mysql-connector-cpp",
        "@nlohmann_json//:json",
    ],
)
