load("@rules_cc//cc:defs.bzl", "cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")

cc_library(
    name = "co_async",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/co_async/**/*.h"]),
    copts = COPTS,
    defines = select({
        "//conditions:default": [],
        "//:debug": ["CO_ASYNC_DEBUG"],
    }),
    strip_include_prefix = "include",
    visibility = ["//co_async:__subpackages__"],
    deps = ["//common:singleton"] + select({
        "//conditions:default": [],
        "//:debug": [
            "//logger",
            "@fmt",
        ],
    }),
)
