load("//build_defs:cpp_opts.bzl", "COPTS")
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files(["LICENSE"])

config_setting(
    name = "debug_build",
    define_values = {"co_async_debug": "true"},
)

cc_library(
    name = "co_async",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/co_async/**/*.h"]),
    copts = COPTS,
    defines = select({
        ":debug_build": ["CO_ASYNC_DEBUG"],
        "//conditions:default": [],
    }),
    includes = ["include"],
    deps = ["//common"] + select({
        ":debug_build": ["//logger"],
        "//conditions:default": [],
    }),
)
