load("//build_defs:cpp_opts.bzl", "COPTS")
load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "design_pattern_test",
    srcs = glob([
        "*_test.cpp",
        "*.h",
    ]),
    copts = COPTS + ["-Wno-non-virtual-dtor"],
    deps = [
        "//common",
        "@glm",
        "@googletest//:gtest_main",
    ],
)
