load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//build_defs:cpp_opts.bzl", "COPTS")

cc_library(
    name = "ziyu_engine",
    srcs = glob(["sunny_land/engine/**/*.cpp"]),
    hdrs = glob(["sunny_land/engine/**/*.h"]),
    copts = COPTS,
    defines = select({
        "//conditions:default": [],
        "//:debug": ["DEBUG_MODE"],
    }),
    features = ["-layering_check"],
    strip_include_prefix = "/sdl3/sunny_land",
    deps = [
        "//common:noncopyable",
        "//common:string_hash",
        "//sdl3",
        "//sdl3:sdl3_image",
        "//sdl3:sdl3_mixer",
        "//sdl3:sdl3_ttf",
        "@fmt",
        "@glm",
        "@nlohmann_json//:json",
        "@spdlog",
    ],
)

cc_library(
    name = "sunny_land_game",
    srcs = glob(["sunny_land/game/**/*.cpp"]),
    hdrs = glob(["sunny_land/game/**/*.h"]),
    copts = COPTS,
    defines = select({
        "//conditions:default": [],
        "//:debug": ["DEBUG_MODE"],
    }),
    features = ["-layering_check"],
    strip_include_prefix = "/sdl3/sunny_land",
    deps = [
        ":ziyu_engine",
        "//common:noncopyable",
        "@fmt",
        "@glm",
        "@nlohmann_json//:json",
        "@spdlog",
    ],
)

cc_binary(
    name = "sunny_land",
    srcs = ["main.cpp"],
    copts = COPTS,
    data = glob(["assets/**"]),
    defines = select({
        "//conditions:default": [],
        "//:debug": ["DEBUG_MODE"],
    }),
    deps = [
        ":sunny_land_game",
        ":ziyu_engine",
        "@bazel_tools//tools/cpp/runfiles",
        "@spdlog",
    ],
)
