load("//build_defs:cpp_opts.bzl", "COPTS")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files(["LICENSE"])

cc_library(
    name = "chat_server_lib",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    copts = COPTS,
    includes = ["include"],
    deps = [
        "//chat/common",
        "//chat/server/common",
        "//chat/server/proto:chat_cc_grpc_proto",
        "//common",
        "//logger",
        "@boost.asio",
        "@boost.uuid",
        "@fmt",
        "@grpc//:grpc++",
        "@nlohmann_json//:json",
    ],
)

cc_binary(
    name = "chat_server",
    srcs = ["chat_server.cpp"],
    copts = COPTS,
    deps = [
        ":chat_server_lib",
    ],
)
