load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//build_defs:cpp_opts.bzl", "COPTS")

package(features = ["-layering_check"])

cc_binary(
    name = "demo",
    srcs = glob([
        "*.cpp",
    ]),
    copts = COPTS,
    data = glob(["assets/**"]),
    deps = [
        "//sdl3",
        "//sdl3:sdl3_image",
        "//sdl3:sdl3_mixer",
        "//sdl3:sdl3_ttf",
        "@fmt",
    ],
)
